apiVersion: v1
appVersion: 6.2.12
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: entando-k8s-controller-coordinator
version: 6.2.12
