apiVersion: v1
kind: ConfigMap
metadata:
  name: entando-docker-image-info
  namespace: {{ .Release.Namespace }}
data:
  app-builder: >-
    {"version":"6.1.318","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-avatar-plugin: >-
    {"version":"6.0.5","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-component-manager: >-
    {"version":"6.2.34","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-de-app-eap: >-
    {"version":"6.3.10","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-de-app-wildfly: >-
    {"version":"6.3.10","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-app-controller: >-
    {"version":"6.2.11","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-app-plugin-link-controller: >-
    {"version":"6.1.3","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-cluster-infrastructure-controller: >-
    {"version":"6.2.8","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-composite-app-controller: >-
    {"version":"6.2.7","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-controller-coordinator: >-
    {"version":"6.2.20","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-database-service-controller: >-
    {"version":"6.2.3","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-dbjob: >-
    {"version":"6.1.4","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-keycloak-controller: >-
    {"version":"6.2.14","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-plugin-controller: >-
    {"version":"6.2.8","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-k8s-service: >-
    {"version":"6.2.1","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-keycloak: >-
    {"version":"6.1.2","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-plugin-sidecar: >-
    {"version":"6.0.2","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  entando-process-driven-plugin: >-
    {"version":"6.1.0","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  busybox: >-
    {"version":"latest","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  mysql-57-centos7: >-
    {"version":"latest","executable-type":"jvm","registry":"docker.io","organization":"entando"}
  postgresql-96-centos7: >-
    {"version":"latest","executable-type":"jvm","registry":"docker.io","organization":"entando"}
