apiVersion: v1
kind: ServiceAccount
metadata:
  name: entando-k8s-service
  namespace: {{ .Release.Namespace }}
  {{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- range $pval := .Values.imagePullSecrets }}
  - name: {{ $pval }}
  {{- end }}
  {{- end }}
